/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.eventloopsoftware.flink.streaming.kotlin

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test
    fun someLibraryMethodReturnsTrue() {
//        val classUnderTest = DataStream<String>()
        assertTrue(1 == 1, "someLibraryMethod should return 'true'")
    }
}
